server:
   port: 8100
   
spring:
  application:
    name: ZuulAppi
    
zuul:
  routes:
    FlightService:
       serviceId: FlightService
    BookingService:
       serviceId: BookingService
    CheckinService:
       serviceId: CheckinService
    UserSerice:
       serviceId: UserService                       

